version: "3.9"

services:

  backend:
    build: ./backend

    ports:
      - "5000:5000"
    
    depends_on:
    - mongodb

    environment:
      MONGO_URI: mongodb://admin:password@mongodb:27017/
      DATABASE_NAME: mern

  mongodb:
    image: mongo:8

    container_name: mongodb

    restart: unless-stopped

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

    volumes:
      - mongo-data:/data/db

  frontend:
    build: ./frontend

    volumes:
      - ./frontend:/app
      - /app/node_modules

    ports:
      - "5173:5173"

    command: npm run dev -- --host 0.0.0.0
    
  nginx:
    image: nginx:latest

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - backend

  prometheus:
    image: prom/prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

    depends_on:
      - backend

  # grafana:
  #   image: grafana/grafana-oss:latest

  #   container_name: grafana

  #   ports:
  #     - "3000:3000"

  #   environment:
  #     GF_SECURITY_ADMIN_USER: admin
  #     GF_SECURITY_ADMIN_PASSWORD: admin

  #   depends_on:
  #     - prometheus

  #   volumes:
  #     - grafana-storage:/var/lib/grafana

volumes:
  mongo-data:
  # grafana-storage: